Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webapp.urls', namespace="webapp"))
]

webapp/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static, settings
from django.views.generic import TemplateView
import views

urlpatterns = [
    url(r'^$', views.UserList.as_view(), name="select"),
    url(r'^upload/$', views.upload, name="upload"),
    url(r'^show/$', views.show, name="showuser"),
    url(r'^staypoints/$', views.stay, name="stay"),
    url(r'^stats/lowbattery/$', views.stay, name="lowbattery"),
    url(r'^stats/$', views.stats, name="stats"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/models.py
from django.db import models


def toint(x):
    try:
        return int(x)
    except ValueError:
        return -1


def tofloat(x):
    try:
        return float(x)
    except ValueError:
        return -1.0


class BaseStation(models.Model):
    # describes a base station record
    rid = models.IntegerField(default=-1)
    email = models.CharField(max_length=100)
    operator = models.CharField(max_length=100)
    mcc = models.IntegerField(default=-1)
    mnc = models.IntegerField(default=-1)
    cid = models.IntegerField(default=-1)
    lac = models.IntegerField(default=-1)
    latitude = models.FloatField(default=-1.0)
    longitude = models.FloatField(default=-1.0)
    timestamp = models.DateTimeField()

    def __str__(self):
        return str(self.rid) + " " + self.email

    def setdata(self, data):
        self.rid = toint(data[0])
        self.email = data[1]
        self.operator = data[2]
        self.mcc = toint(data[3])
        self.mnc = toint(data[4])
        self.cid = toint(data[5])
        self.lac = toint(data[6])
        self.latitude = tofloat(data[7])
        self.longitude = tofloat(data[8])
        self.timestamp = data[9] + "+03:00"


class BatteryStatus(models.Model):
    # describes a battery status record
    rid = models.IntegerField(default=-1)
    email = models.CharField(max_length=100)
    level = models.IntegerField(default=-1)
    plugged = models.IntegerField(default=-1)
    temperature = models.IntegerField(default=-1)
    voltage = models.IntegerField(default=-1)
    timestamp = models.DateTimeField()

    def __str__(self):
        return str(self.rid) + " " + self.email

    def setdata(self, data):
        self.rid = toint(data[0])
        self.email = data[1]
        self.level = toint(data[2])
        self.plugged = toint(data[3])
        self.temperature = toint(data[4])
        self.voltage = toint(data[5])
        self.timestamp = data[6] + "+03:00"


class GPSStatus(models.Model):
    #describes a GPS position record
    rid = models.IntegerField(default=-1)
    email = models.CharField(max_length=100)
    latitude = models.FloatField(default=-1.0)
    longitude = models.FloatField(default=-1.0)
    timestamp = models.DateTimeField()

    def __str__(self):
        return str(self.rid) + " " + self.email

    def setdata(self, data):
        self.rid = toint(data[0])
        self.email = data[1]
        self.latitude = tofloat(data[2])
        self.longitude = tofloat(data[3])
        self.timestamp = data[4] + "+03:00"


class WifiPos(models.Model):
    #descibes a wifi position (average of positions from wifi statuses)
    ssid = models.CharField(max_length=100)
    bssid = models.CharField(max_length=100)
    latitude = models.FloatField(default=-1.0)
    longitude = models.FloatField(default=-1.0)

    def __str__(self):
        return self.ssid + " - " + self.bssid


class WifiStatus(models.Model):
    #descibes a wifi status record
    rid = models.IntegerField(default=-1)
    email = models.CharField(max_length=100)
    ssid = models.CharField(max_length=100)
    bssid = models.CharField(max_length=100)
    level = models.IntegerField(default=-1)
    frequency = models.IntegerField(default=-1)
    latitude = models.FloatField(default=-1.0)
    longitude = models.FloatField(default=-1.0)
    timestamp = models.DateTimeField()
    realpos = models.ForeignKey(WifiPos, null=True, blank=True)

    def __str__(self):
        return str(self.rid) + " " + self.email

    def setdata(self, data):
        self.rid = toint(data[0])
        self.email = data[1]
        self.ssid = data[2]
        self.bssid = data[3]
        self.level = toint(data[4])
        self.frequency = toint(data[5])
        self.latitude = tofloat(data[6])
        self.longitude = tofloat(data[7])
        self.timestamp = data[8] + "+03:00"

webapp/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.views.generic import ListView
from django.db.models import Count, Avg
from django.db.models.functions import Lower
from models import *
from django.db import transaction
from sklearn.cluster import DBSCAN
import django.db.models
import django.utils.timezone
import django.core.exceptions
import django.db.models
import math
import datetime
import time


class UTC0030(datetime.tzinfo):
    _offset = datetime.timedelta(hours=3)
    _dst = datetime.timedelta(0)
    _name = "+0030"

    def utcoffset(self, dt):
        return self.__class__._offset

    def dst(self, dt):
        return self.__class__._dst

    def tzname(self, dt):
        return self.__class__._name


class UserList(ListView):
    #context is the list of users
    queryset = BatteryStatus.objects.values("email").distinct()
    template_name = "webapp/select.html"

    def get_context_data(self, **kwargs):
        #set 1/1/2015 and current date as the default start and end dates
        context = super(ListView, self).get_context_data(**kwargs)
        context['curdate'] = datetime.datetime.now()
        context['olddate'] = datetime.datetime(year=2015, month=1, day=1)
        return context


def saveobjects(data, name):
    #save one type of file to the database
    nametoobj = {"bsobjects": BaseStation, "batteryobjects": BatteryStatus, "gpsobjects": GPSStatus,
                 "wifiobjects": WifiStatus}
    if name not in nametoobj:
        return
    print "Updating " + name
    objtype = nametoobj[name]
    iterdata = iter(data)
    objtype.objects.all().delete()
    #skip the first line of the file
    next(iterdata)
    with transaction.atomic():
        for line in iterdata:
            if line[-1] == '\n':
                line = line[:-1]
            #split the parameters and pass them to the object's setdata function
            data = line.split("\t")
            try:
                obj = objtype()
                obj.setdata(data)
                obj.save()
            except django.core.exceptions.ValidationError:
                print "Validation error"
            except IndexError:
                print "Out of array range"


def upload(request):
    uploaded = False
    if request.method == "POST":
        #handle uploaded files
        for key, val in request.FILES.iteritems():
            saveobjects(val, key)
            uploaded = True
            #if a wifi file was uploaded, update the averaged wifi positions in the database
            if key == "wifiobjects":
                wmap = dict({})
                #save all the positions found for each access point
                for w in WifiStatus.objects.all():
                    if w.bssid not in wmap:
                        wmap[w.bssid] = (w.ssid, [(math.pow(10, float(w.level) / 10), w.latitude * math.pi / 180,
                                                   w.longitude * math.pi / 180)])
                    else:
                        wmap[w.bssid][1].append((math.pow(10, float(w.level) / 10), w.latitude * math.pi / 180,
                                                 w.longitude * math.pi / 180))
                with transaction.atomic():
                    for wkey, wval in wmap.iteritems():
                        lat = 0
                        lon = 0
                        totalw = 0
                        #add all latitudes and longitudes for each AP
                        for i in wval[1]:
                            if i[1] != -1.0 and i[2] != -1.0:
                                lat += i[0] * i[1]
                                lon += i[0] * i[2]
                                totalw += i[0]
                        try:
                            #save the average in the database
                            wp = WifiPos(bssid=wkey, ssid=wval[0], latitude=(lat / totalw) * 180 / math.pi,
                                         longitude=(lon / totalw) * 180 / math.pi)
                            wp.save()
                            wsset = WifiStatus.objects.filter(bssid=wkey)
                            wsset.update(realpos=wp)
                        except ZeroDivisionError:
                            print "Error finding access point position"
    return render(request, "webapp/upload.html", {"uploadsucc": uploaded})


def show(request):
    #get POST parameters
    u = request.POST.get("user", "")
    strstart = request.POST.get("start", "01/01/1990")
    strend = request.POST.get("end", "01/01/2100")
    sdate = datetime.datetime(*time.strptime(strstart, "%d/%m/%Y")[:3], tzinfo=UTC0030())
    edate = datetime.datetime(*time.strptime(strend, "%d/%m/%Y")[:3], tzinfo=UTC0030())
    #filter wifi statuses by date and email
    wifires = WifiStatus.objects.filter(email=u, timestamp__gte=sdate, timestamp__lte=edate)
    wifistats = list(wifires.values("ssid", "bssid", "realpos__latitude", "realpos__longitude", "timestamp"))
    #find average RSSI and frequency for each AP
    avgs = dict([(x['bssid'], (x['RSSI'], x['freq'])) for
                 x in list(wifires.values("bssid").annotate(RSSI=Avg("level"), freq=Avg("frequency")))])
    for i in wifistats:
        i['RSSI'] = avgs[i['bssid']][0]
        i['freq'] = avgs[i['bssid']][1]
    #filter GPS and base station statuses
    gpsres = list(GPSStatus.objects.filter(email=u, timestamp__gte=sdate, timestamp__lte=edate).order_by("timestamp"))
    bssres = BaseStation.objects.filter(email=u, timestamp__gte=sdate, timestamp__lte=edate)
    bssres = bssres.exclude(latitude=-1.0).exclude(longitude=-1.0)
    sr = BatteryStatus.objects.filter(email=u, timestamp__gte=sdate, timestamp__lte=edate).order_by('timestamp')
    #format each date to a string
    data = map(lambda t: [t.timestamp.astimezone(UTC0030()).strftime("%d-%m-%y %H:%M"), t.level], sr)
    #create context from data
    ctx = {"wifi": wifistats, "gps": gpsres, "bss": bssres, "data": data}
    if request.POST.get("bestpath", "") == "on":
        #if the option to find the path with the least battery consumption is set
        bestpath = []
        #for each point visited
        for i in gpsres:
            bestv = -1
            bestt = (0, 0)
            for j in wifistats:
                #check only APs with timestamps less than an hour apart from the current point
                if abs((i.timestamp - j['timestamp']).total_seconds()) > 3600:
                    continue
                #find squared distance of current point to AP
                pdist = (math.cos((i.latitude+j['realpos__latitude'])/2) * (j['realpos__longitude']-i.longitude))**2 + \
                    (j['realpos__latitude']-i.latitude)**2
                #use time difference + RSSI*10 + distance*10000000 as the metric
                cur = abs((i.timestamp - j['timestamp']).total_seconds()) + abs(j['RSSI']) * 10 + pdist*10000000
                #find the best AP
                if bestv == -1 or cur < bestv:
                    bestv = cur
                    bestt = (j['realpos__latitude'], j['realpos__longitude'])
            #if an AP was found, add it to the list
            if bestv != -1 and (len(bestpath) == 0 or bestpath[-1] != bestt):
                bestpath.append(bestt)
        ctx['bestpath'] = bestpath
    return render(request, "webapp/tracking.html", ctx)


def centroid(points):
    #if no points
    if len(points) == 0:
        return 0.0, 0.0, 0, 0
    lats = [x.latitude for x in points]
    lons = [x.longitude for x in points]
    #average points and return first and last timestamp
    return sum(lats)/len(lats), sum(lons)/len(lons), points[0].timestamp, points[-1].timestamp


def clusterarea(points):
    z = zip(*points)
    lats = z[0]
    lons = z[1]
    #average points and return the top-left and bottom-right corners of the cluster area rectangle
    return sum(lats)/len(lats), sum(lons)/len(lons), min(lats), min(lons), max(lats), max(lons)


def haversine(p1, p2):
    #haversine formula - find distance between two (lat, long) pairs
    r = 6371000
    f1 = p1.latitude * math.pi / 180
    f2 = p2.latitude * math.pi / 180
    df = (p1.latitude-p2.latitude) * math.pi / 180
    dl = (p1.longitude-p2.longitude) * math.pi / 180
    a = math.sin(df/2)**2 + math.cos(f1)*math.cos(f2)*math.sin(dl/2)**2
    c = 2*math.atan2(math.sqrt(a), math.sqrt(1-a))
    return r*c


def find_stay_points(points, dmax, tmin, tmax):
    #stay points algorithm
    lsp = []
    i = 0
    n = len(points)
    while i < n-1:
        for j in range(i+1, n):
            if points[j].timestamp-points[j-1].timestamp > tmax:
                if points[j-1].timestamp-points[i].timestamp > tmin:
                    lsp.append(centroid(points[i:j]))
                i = j
                break
            elif haversine(points[i], points[j]) > dmax:
                if points[j-1].timestamp-points[i].timestamp > tmin:
                    lsp.append(centroid(points[i:j]))
                    i = j
                    break
                i += 1
                break
            elif j == n-1:
                if points[j].timestamp-points[i].timestamp > tmin:
                    lsp.append(centroid(points[i:]))
                i = j
                break
    return lsp


def stay(request):
    strstart = request.POST.get("start", "01/01/1990")
    strend = request.POST.get("end", "01/01/2100")
    try:
        #get POST parameters
        sdate = datetime.datetime(*time.strptime(strstart, "%d/%m/%Y")[:3], tzinfo=UTC0030())
        edate = datetime.datetime(*time.strptime(strend, "%d/%m/%Y")[:3], tzinfo=UTC0030())
        dmax = int(request.POST.get("dmax", 10))
        tmin = datetime.timedelta(hours=int(request.POST.get("tmin", 10)))
        tmax = datetime.timedelta(hours=int(request.POST.get("tmax", 10)))
    except ValueError:
        return HttpResponse("Only numbers allowed!")
    if "stay" in request.POST:
        #find stay points
        u = request.POST.get("user", "")

webapp/templates/webapp/clusters.html
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
{% load staticfiles %}
{% load leaflet_tags %}
<script>
	function map_init_basic (map, options) {
		var markers = [];
		{% if points %}
		var wifiicon = new L.icon({iconUrl: '{% static "webapp/ap.ico" %}', iconSize: [15, 15]});
		{% for i in points %}
		L.marker([{{ i.latitude }}, {{ i.longitude }}], {icon: wifiicon, title: 'SSID = {{ i.ssid }}, Channel = {{ i.channel }}'}).addTo(map);
		{% endfor %}
		{% endif %}
		{% for i in areas %}
		markers.push(new L.marker([{{ i.0 }}, {{ i.1 }}]).addTo(map));
		{% endfor %}
		var feats = L.featureGroup(markers);
		{% for i in areas %}
		L.rectangle([[{{ i.2 }},{{ i.3 }}],[{{ i.4 }},{{ i.5 }}]]).addTo(map);
		{% endfor %}
		var feats = L.featureGroup(markers);
		var sw = feats.getBounds().getSouthWest(), ne = feats.getBounds().getNorthEast();
		if (Math.abs(sw.lat - ne.lat) < 0.002) {
			sw.lat -= 0.001;
			ne.lat += 0.001;
		}
		if (Math.abs(sw.lon - ne.lon) < 0.002) {
			sw.lon -= 0.001;
			ne.lon += 0.001;
		}
		map.fitBounds(L.latLngBounds(sw, ne));
    }
    </script>
    {% leaflet_js %}
    {% leaflet_css %}
</head>
<body>
{% leaflet_map "clustermap" callback="window.map_init_basic" %}
<script type="text/javascript">
$("#clustermap").height($(window).height()*90/100).width($(window).width()*90/100);
map.invalidateSize();
</script>
</body>
</html>

webapp/templates/webapp/select.html
<!doctype html>
<html lang="en" style="width:100%;height:100%">
<head>
  <meta charset="utf-8">
  <title>Network Management Project</title>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
  $(function() {
    $( "#datepicker1" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#datepicker2" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#datepicker3" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#datepicker4" ).datepicker({ dateFormat: 'dd/mm/yy' });
  });
  </script>
</head>
<body style="height:100%">
<div style="width:100%;height:100%">
<div style="float:left;width:20%;height:100%">
<form action="{% url 'webapp:showuser' %}" method="post" target="tframe">
{% csrf_token %}
<select name="user">
{% for u in object_list %}
<option value="{{ u.email }}">{{ u.email }}</option>
{% endfor %}
</select>
<p>Start date: <input type="text" id="datepicker1" name="start" value="{{ olddate|date:'d/m/Y' }}" readonly /></p>
<p>End date: <input type="text" id="datepicker2" name="end" value="{{ curdate|date:'d/m/Y' }}" readonly /></p>
<p><input type="checkbox" name="bestpath" /> Show best path for least battery consumption</p>
<input type="submit" value="Go" />
</form> 
<hr />
<form action="{% url 'webapp:stay' %}" method="post" target="tframe">
{% csrf_token %}
<p>Dmax (meters): <input type="text" pattern="\d+" title="Enter a number" name="dmax" value="10000" /></p>
<p>Tmin (hours): <input type="text" pattern="\d+" title="Enter a number" name="tmin" value="12" /></p>
<p>Tmax (hours): <input type="text" pattern="\d+" title="Enter a number" name="tmax" value="72" /></p>
<p>Start date: <input type="text" id="datepicker3" name="start" value="{{ olddate|date:'d/m/Y' }}" readonly /></p>
<p>End date: <input type="text" id="datepicker4" name="end" value="{{ curdate|date:'d/m/Y' }}" readonly /></p>
<select name="user">
{% for u in object_list %}
<option value="{{ u.email }}">{{ u.email }}</option>
{% endfor %}
</select>&nbsp;<input type="submit" value="Show stay points" name="stay" />
<br /><br />
<p>Epsilon: <input type="text" pattern="[0-9]+([\.|,][0-9]+)?" title="Enter a floating point number" name="eps" value="0.01" /></p>
<p>Minimum points: <input type="text" pattern="\d+" title="Enter a number" name="minpts" value="5" /></p>
<p><input type="checkbox" name="placeaps" /> Place 2 new APs with minimum interference</p>
<input type="submit" value="Show points of interest for all users" name="poi" />
</form>
<hr />
<a href="{% url 'webapp:stats' %}" target="tframe">Show stats</a>
</div>
<div style="float:right;width:80%;height:100%">
<iframe src="" style="height:100%;width:100%" name="tframe"></iframe>
</div>
</div>
</body>
</html>

webapp/templates/webapp/show1st.html
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
{% load staticfiles %}
{% load leaflet_tags %}
{% load chartit %}
{{ chart|load_charts:"container" }}
<script>
	function map_init_basic (map, options) {
		var wifiicon = new L.icon({iconUrl: '{% static "webapp/wifi.ico" %}'});
		var bssicon = new L.icon({iconUrl: '{% static "webapp/bss.gif" %}'});
		var markers = [{% for i in wifi %}new L.marker([{{ i.realpos__latitude }}, {{ i.realpos__longitude }}], {icon:wifiicon, riseOnHover: true, title: 'SSID = {{ i.ssid }}, RSSI = {{ i.RSSI }}, Freq = {{ i.frequency }}Hz'}),{% endfor %}]
		{% for i in bss %}
		markers.push(new L.marker([{{ i.latitude }}, {{ i.longitude }}], {riseOnHover: true, title: 'Operator = {{ i.operator }}, MCC = {{ i.mcc }}, MNC = {{ i.mnc }}, CID = {{ i.cid }}, LAC = {{ i.lac }}', icon: bssicon}));
		{% endfor %}
		latlngs = [{% for i in gps %}new L.LatLng({{ i.latitude }}, {{ i.longitude }}),{% endfor %}];
		var polyline = L.polyline(latlngs, {color: 'red'});
		markers.push(polyline);
		var feats = L.featureGroup(markers);
		feats.addTo(map);
		map.fitBounds(feats.getBounds().pad(0.2));
    }
    </script>
    {% leaflet_js %}
    {% leaflet_css %}
</head>
<body>
{% leaflet_map "yourmap" callback="window.map_init_basic" %}
<br />
<div id='container'></div>
</body>
</html>

webapp/templates/webapp/stats.html
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script>
	google.load("visualization", "1", {packages:["corechart", "bar"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {

		var data = google.visualization.arrayToDataTable([
			['Hour', 'Low battery count'],
			{% for x in batterychart %}
			['{{ x.hr }}', {{ x.c }}],
			{% endfor %}
			]);

		var options = {
			bars: 'vertical',
			hAxis: {title: 'Hour'}
		};

		var mat = new google.visualization.ColumnChart(document.getElementById('battery_chart'));
		mat.draw(data, options);

		var data2 = google.visualization.arrayToDataTable([
			['Operator', 'Cell count'],
			{% for x in operators %}
			['{{ x.0 }}', {{ x.1 }}],
			{% endfor %}
			]);

		var options2 = {
			bars: 'horizontal',
			hAxis: {title: 'Operator', showTextEvery: 1},
			vAxis: {title: 'Count'}
		};

		var mat2 = new google.charts.Bar(document.getElementById('operator_chart'));
		mat2.draw(data2, options2);
	}
</script>
</head>
<body>
<div id="battery_chart" style="width: 90%; height: 200px;"></div><br /><hr /><br />
<div id="operator_chart" style="width: 90%; height: 200px;"></div>
</body>
</html>

webapp/templates/webapp/staypoints.html
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
{% load staticfiles %}
{% load leaflet_tags %}
<script>
	function map_init_basic (map, options) {
		var markers = [];
		{% for i in lsp %}
		markers.push(new L.marker([{{ i.0 }}, {{ i.1 }}], {riseOnHover: true, title: 'Stayed from {{ i.2 }} to {{ i.3 }}'}).addTo(map));
		{% endfor %}
		var feats = L.featureGroup(markers);
		var sw = feats.getBounds().getSouthWest(), ne = feats.getBounds().getNorthEast();
		if (Math.abs(sw.lat - ne.lat) < 0.002) {
			sw.lat -= 0.001;
			ne.lat += 0.001;
		}
		if (Math.abs(sw.lon - ne.lon) < 0.002) {
			sw.lon -= 0.001;
			ne.lon += 0.001;
		}
		map.fitBounds(L.latLngBounds(sw, ne));
    }
    </script>
    {% leaflet_js %}
    {% leaflet_css %}
</head>
<body>
{% leaflet_map "staymap" callback="window.map_init_basic" %}
<script type="text/javascript">
$("#staymap").height($(window).height()*90/100).width($(window).width()*90/100);
map.invalidateSize();
</script>
</body>
</html>

webapp/templates/webapp/tracking.html
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
{% load staticfiles %}
{% load leaflet_tags %}
<script>
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {

		var data = google.visualization.arrayToDataTable([
			['Timestamp', 'Battery'],
			{% for x in data %}
			["{{ x.0 }}", {{ x.1 }}],
			{% endfor %}
			]);

		var options = {
			title: 'Battery levels per timestamp',
			hAxis: {title: 'Timestamp'},
			vAxis: {title: 'Level', minValue: 0, maxValue: 100}
		};

		var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
		chart.draw(data, options);
	}
	function map_init_basic (map, options) {
		var wifiicon = new L.icon({iconUrl: '{% static "webapp/ap.ico" %}', iconSize: [15, 15]});
		var bssicon = new L.icon({iconUrl: '{% static "webapp/bss.ico" %}', iconSize: [25, 25]});
		var markers = [];
		{% for i in wifi %}
		markers.push(new L.marker([{{ i.realpos__latitude }}, {{ i.realpos__longitude }}], {icon:wifiicon, riseOnHover: true, title: 'SSID = {{ i.ssid }}, RSSI = {{ i.RSSI }}, Freq = {{ i.freq }}MHz'}).addTo(map));
		{% endfor %}
		{% for i in bss %}
		markers.push(new L.marker([{{ i.latitude }}, {{ i.longitude }}], {riseOnHover: true, title: 'Operator = {{ i.operator }}, MCC = {{ i.mcc }}, MNC = {{ i.mnc }}, CID = {{ i.cid }}, LAC = {{ i.lac }}', icon: bssicon}).addTo(map));
		{% endfor %}
		latlngs = [];
		{% for i in gps %}
		latlngs.push(new L.LatLng({{ i.latitude }}, {{ i.longitude }}));
		{% endfor %}
		{% if bestpath %}
		var bestpoints = [];
		var circleicon = new L.icon({iconUrl: '{% static "webapp/circle.png" %}', iconSize: [25, 25]});
		{% for i in bestpath %}
		bestpoints.push(new L.LatLng({{ i.0 }}, {{ i.1 }}));
		new L.marker([{{ i.0 }}, {{ i.1 }}], {icon: circleicon, zIndexOffset: -1000}).addTo(map)
		{% endfor %}
		L.polyline(bestpoints, {color: 'black', weight: '2', dashArray: '5,5'}).addTo(map);
		markers.push()
		{% endif %}
		var polyline = L.polyline(latlngs, {color: 'red'}).addTo(map);
		markers.push(polyline);
		var feats = L.featureGroup(markers);
		var sw = feats.getBounds().getSouthWest(), ne = feats.getBounds().getNorthEast();
		if (Math.abs(sw.lat - ne.lat) < 0.002) {
			sw.lat -= 0.001;
			ne.lat += 0.001;
		}
		if (Math.abs(sw.lon - ne.lon) < 0.002) {
			sw.lon -= 0.001;
			ne.lon += 0.001;
		}
		map.fitBounds(L.latLngBounds(sw, ne));
    }
    </script>
    {% leaflet_js %}
    {% leaflet_css %}
</head>
<body>
{% leaflet_map "trackingmap" callback="window.map_init_basic" %}
<script type="text/javascript">
$("#trackingmap").height($(window).height()*60/100).width($(window).width()*90/100);
map.invalidateSize();
</script>
<br />
<div id="chart_div" style="width: 100%; height: 500px;"></div>
</body>
</html>

webapp/templates/webapp/upload.html
{% if uploadsucc %}
Upload successful!<br />
{% endif %}
<form action="" enctype="multipart/form-data" method="POST">
{% csrf_token %}
Base stations: <input type="file" name="bsobjects" /><br />
Battery: <input type="file" name="batteryobjects" /><br />
GPS: <input type="file" name="gpsobjects" /><br />
Wifi: <input type="file" name="wifiobjects" /><br />
<input type="submit" />
</form>